### ISSUE TITLE
UI regression from 1.1.3?

### ISSUE THREAD

**Issue by ice051128** [sapondanaisriwan/Youtube-Old-Layout#1]
The latest update has unrounded the control buttons (volume slider, quality settings, etc) within the video player itself which is contrary to what the old layout looked like, see below screenshot for reference.

![Screenshot_1](https://user-images.githubusercontent.com/49018832/200007047-c92b4af4-b4b7-4a34-9de1-e34ef630dcbf.png)

**Comment by sapondanaisriwan** [comment]
I appreciate your reporting this problem to me, now the problem is solved
![image](https://user-images.githubusercontent.com/64634605/200015283-5c4c4a7c-1f6b-4a30-a96c-15f54d9b38b3.png)
