### ISSUE TITLE
Centered search results on youtube

### ISSUE THREAD

**Issue by ice051128** [sapondanaisriwan/Youtube-Old-Layout#2]
Youtube has updated the UI once again and now the search results are no longer centered. The old UI used to have a lot of padding on the left side so the search results are centered. Will it be possible to implement centered search results in the next update?

What it looks like now:
![image](https://user-images.githubusercontent.com/49018832/201268153-9a692d7c-5b25-4f82-8112-6f0d7db2e907.png)

What it used to look like from what I can find on the internet:
https://storage.googleapis.com/support-forums-api/attachment/thread-51221404-7061916441851235437.png

**Comment by sapondanaisriwan** [comment]
I tried to center it, but it looks so weird.
![image](https://user-images.githubusercontent.com/64634605/201272539-6239bd9f-7bbe-4bec-b418-b5202408cff1.png)

**Comment by ice051128** [comment]
> I tried to center it, but it looks so weird. ![image](https://user-images.githubusercontent.com/64634605/201272539-6239bd9f-7bbe-4bec-b418-b5202408cff1.png)

I don't think that looks weird. At even higher resolutions, you can get something like this:
https://i.redd.it/zxc4dwgxd8z91.jpg

**Comment by ice051128** [comment]
Closed since they reverted the UI change/bug now

**Comment by ice051128** [comment]
The issue is back. Not sure if youtube has finalized the decision to align the search results to the left, but it would be great to have a toggle to align the search results to the center regardless. https://www.reddit.com/r/youtube/comments/yt167k/who_came_up_with_this_idea/

**Comment by sapondanaisriwan** [comment]
All right
![image](https://user-images.githubusercontent.com/64634605/201518032-e6c7f658-223a-4c5d-8871-eeb3ee5bcb68.png)

**Comment by sapondanaisriwan** [comment]
While watching some random videos, I got duplicate videos on the watchpage. Perhaps it's the bug of itself.
![image](https://user-images.githubusercontent.com/64634605/204131174-823a3176-6ce4-4a76-bb38-3d7b02cb89da.png)
