### ISSUE TITLE
Thumbnails are shrunk on home page

### ISSUE THREAD

**Issue by ice051128** [sapondanaisriwan/Youtube-Old-Layout#3]
Off:
![Screenshot_1](https://user-images.githubusercontent.com/49018832/201512461-365db5ef-abb1-439c-8a1c-dc3292cf7b30.png)

On:
![Screenshot_2](https://user-images.githubusercontent.com/49018832/201512469-a6cfbab7-d2bd-42b0-bb7b-de5a3ddecd00.png)

Even though the thumbnails are rounded, but the thumbnails and margins are also shrunk which shouldn't be the case.

**Comment by sapondanaisriwan** [comment]
It's a feature. I did that because I prefer not have margins than have them. 😂
